### PR TITLE
Fix/duplicate bom

### LINKED ISSUE #947: Erroneously adds an unreadable character at the beginning of the first line.
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

DeepSeek 2.5, Gemini-2.0-flash

### What happened?

When a file is being edited in C# projects, for some reason invisible characters are added at the beginning of the first line, which leads to a language server error, which goes to a request in Cline and the model tries to remove this character in an endless loop

image

### Steps to reproduce

1.
2.
3.

### Relevant API REQUEST output

_No response_

### Additional context

_No response_

### LINKED ISSUE #2463: Cline inserts second BOM 0xFEFF in csproj files corrupting them
### What happened?

When Cline directly edits .csproj files on Windows (could be other files too) for some reason it inserts a second BOM character at the start of the file and then it cannot be read by Visual Studio. 

### Steps to reproduce

1. Create a new csproj file  - dotnet new console -o test
2. Ask Cline to add a package like Xunit to that file without using any dotnet tools, just edit it
3. If the file had a BOM character it will now have two. If it didn't have any BOM character it remains without one.

### Relevant API REQUEST output

```shell

```

### Operating System

Windows 11

### Cline Version

3.8.3

### Additional context

This has occurred for a while and is unrelated to the recent releases

### PR DESCRIPTION
**Pull request by bamps53**
### Description

Fixes a bug in `DiffViewProvider` where editing a file with a Byte Order Mark (BOM) could result in a duplicate BOM being inserted into the document buffer during the streaming update process.

The issue occurred because:
1. Incoming content (`accumulatedContent`) contained a BOM when the original file has BOM.
2. `vscode.workspace.applyEdit`, when replacing content from the start of the file (0,0), might also implicitly preserve or add a BOM based on the original file's state.

This combination led to two BOMs (`\ufeff\ufeff`) appearing at the beginning of the buffer.

The fix involves unconditionally stripping any leading BOM from the `accumulatedContent` within the `update` method *before* it is passed to `applyEdit`. This prevents the duplication, relying on `applyEdit` and the later `saveChanges` method to correctly handle the final BOM state based on the original file's requirements.

**Related Issues:**
*   Fixes #947
*   Fixes #2463

### Test Procedure

The issue was identified and debugged through interactive testing and analysis of the `applyEdit` behavior with BOM files.

**Steps to reproduce the bug (before fix) and verify the fix:**

1.  Create a file named `temp.txt` with the following content:
    ```
    a
    b
    c
    ```
2.  In VS Code, change the file encoding to "UTF-8 with BOM". (Click on the encoding in the status bar, select "Save with Encoding", choose "UTF-8 with BOM").
3.  Ask Cline to perform an edit, for example: "replace c with d in temp.txt".

**Expected behavior:**
*   **Before fix:** During the streaming update in the diff view, a duplicate BOM (`\ufeff\ufeff`) might appear at the beginning of the file content in the editor buffer. The final saved file might also contain issues depending on subsequent save logic.
*   **After fix:** The streaming update proceeds without inserting a duplicate BOM. The final saved file correctly contains only a single BOM.

Manual testing confirmed that editing a BOM file no longer results in duplicate BOMs in the editor buffer during streaming updates, and the final saved file correctly retains the single BOM.

### Type of Change

-   [x] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [ ] ✨ New feature (non-breaking change which adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] 📚 Documentation update

### Pre-flight Checklist

-   [x] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [x] Tests are passing (`npm test`) and code is formatted and linted (`npm run format && npm run lint`)
-   [x] I have created a changeset using `npm run changeset` (required for user-facing changes)
-   [x] I have reviewed [contributor guidelines](https://github.com/cline/cline/blob/main/CONTRIBUTING.md)

### Screenshots

N/A

----

> [!IMPORTANT]
> Fixes duplicate BOM issue in `DiffViewProvider` by stripping BOM from `accumulatedContent` in `update()` method.
> 
>   - **Bug Fix**:
>     - In `DiffViewProvider`, `update()` method now strips leading BOM from `accumulatedContent` to prevent duplicate BOMs during streaming updates.
>     - Relies on `applyEdit` and `saveChanges` to handle BOM based on original file state.
>   - **Related Issues**:
>     - Fixes #947
>     - Fixes #2463
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=cline%2Fcline&utm_source=github&utm_medium=referral)<sup> for 943a190f6b7b66012d5ebb6732b0cdabaeeaf0a2. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by dcbartlett — APPROVED** [review]

**Review by dcbartlett — APPROVED** [review]

File: src/integrations/editor/DiffViewProvider.ts [hunk 1]
```diff
@@ -79,6 +79,15 @@ export class DiffViewProvider {
...
 			throw new Error("Required values not set")
 		}
+
+		// --- Fix to prevent duplicate BOM ---
+		// Strip potential BOM from incoming content. VS Code's `applyEdit` might implicitly handle the BOM
+		// when replacing from the start (0,0), and we want to avoid duplication.
+		// Final BOM is handled in `saveChanges`.
+		if (accumulatedContent.startsWith("\ufeff")) {
+			accumulatedContent = accumulatedContent.slice(1) // Remove the BOM character
+		}
```
Comment (dcbartlett) [inline src/integrations/editor/DiffViewProvider.ts:89]: Looking at the logic here, I feel this condition is incorrect.  This will remove the `\ufeff` character from a file that ONLY had 1 at the beginning.
```suggestion
		if (accumulatedContent.startsWith("\ufeff\ufeff")) {
			accumulatedContent = accumulatedContent.slice(1) // Remove the BOM character
		}
```

Comment (dcbartlett) [reply src/integrations/editor/DiffViewProvider.ts:89]: This also is a pragmatic fix to an agentic problem.  While this will correct the output, we should try to fix the underlying problem with what is causing the model to provide this in the first place.

**Review by dcbartlett — CHANGES_REQUESTED** [review]

File: src/integrations/editor/DiffViewProvider.ts (hunk 1 above)
Comment (bamps53) [reply src/integrations/editor/DiffViewProvider.ts:89]: @dcbartlett 

> Looking at the logic here, I feel this condition is incorrect. This will remove the \ufeff character from a file that ONLY had 1 at the beginning.

No, as I mentioned in the comment, VS Code's `applyEdit` might implicitly handle the BOM. This means VS Code is aware of the original file encoding and preserves the BOM if the file is UTF-8 with BOM. Therefore, when using `vscode.workspace.applyEdit(edit)`, the edit is expected to contain no BOM in the input.


> This also is a pragmatic fix to an agentic problem. While this will correct the output, we should try to fix the underlying problem with what is causing the model to provide this in the first place.

Makes sense. I think the real issue is a mismatch between the read and write APIs. When reading the file content, it uses `fs.readFile` with UTF-8 encoding, but when writing, it uses `vscode.workspace.applyEdit`. Somehow, `fs.readFile` treats the BOM as part of the text, which is why the BOM ends up in the content.

This also fixes the problem:

```
			// this.originalContent = await fs.readFile(absolutePath, "utf-8")
			const fileUri = vscode.Uri.file(absolutePath);
			const fileContentUint8Array = await vscode.workspace.fs.readFile(fileUri);
			const decoder = new TextDecoder('utf-8');  // handles BOM correctly
			this.originalContent = decoder.decode(fileContentUint8Array);
```

You can see it at this line:  
https://github.com/cline/cline/blob/6e40ec16f3d2cfb173fbf45c2339a0b69cfa487a/src/integrations/editor/DiffViewProvider.ts#L46

But I didn't want to change only this one among many uses of `fs.readFile`. So I placed my PR close to where the issue actually happens (inside of `update` func).

**Review by dcbartlett — APPROVED** [review]

**Review by celestial-vault — APPROVED** [review]

**Comment by saoudrizwan** [comment]
Incredible, I was not able to produce this issue personally so appreciate you investigating 🙌
