### PR TITLE
Permissions issue when initializing checkpoints

### LINKED ISSUE #2322: API Request Loading Indefinitely
### What happened?

API Request is loading indefinitely in VS Code.

### Steps to reproduce

1. Prompt: Review the current stage and suggest next steps
2.Model: Claude 3.7 Sonnet:Beta
3.IDE: VS Code on Ubuntu

### Relevant API REQUEST output

```shell

```

### Operating System

Pop OS 22.04

### Cline Version

3.7.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by canvrno**
### Description

Users reported issues with checkpoints related to permissions in the workspace. It was found that this was due to permissions, as users were able to bypass this issue by either changing permissions or disabling checkpoints. This PR makes changes to check that we have the necessary permissions and add what files we can.

The legacy checkpoints implementation would ignore these errors, and end up tracking no files/creating no checkpoints. These changes will proceed with checkpoints, including files where possible.

Fixes #2322, #2239 

### Test Procedure

Modify a workspace such that VS Code/Cline is not able to access any files (_sudo chmod 000 <workspace>_), then start a new task with file modification goals. It will not succeed, but it should not hang.

Modify a workspace such that some files and folders are not accessible (_sudo chmod 000 <file/dir>_), and perform the same test. It should proceed, and if you check the checkpoints shadow git in globalStorage it should be tracking the files it is able to access (_git ls-files)_. Restoring from a checkpoint should only restore the tracked files.

### Type of Change

-   [X] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [ ] ✨ New feature (non-breaking change which adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] 📚 Documentation update

### Pre-flight Checklist

-   [X] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [X] Tests are passing (`npm test`) and code is formatted and linted (`npm run format && npm run lint`)
-   [X] I have created a changeset using `npm run changeset` (required for user-facing changes)
-   [X] I have reviewed [contributor guidelines](https://github.com/cline/cline/blob/main/CONTRIBUTING.md)

### Additional Notes

----

> [!IMPORTANT]
> Adds permissions checks and error handling to checkpoint initialization and file addition, allowing partial file tracking when some files are inaccessible.
> 
>   - **Behavior**:
>     - Adds permissions checks in `getWorkingDirectory()` in `CheckpointUtils.ts` to ensure workspace accessibility.
>     - Modifies `addCheckpointFiles()` in `CheckpointGitOperations.ts` to continue adding accessible files despite errors.
>     - Updates `initShadowGit()` in `CheckpointGitOperations.ts` to handle file addition failures gracefully.
>   - **Error Handling**:
>     - Introduces error handling in `addCheckpointFiles()` and `initShadowGit()` to log errors and proceed with accessible files.
>     - Logs errors in `commit()` in `CheckpointTracker.ts` if file addition fails.
>   - **Misc**:
>     - Adds `--ignore-errors` option to `git.add()` in `CheckpointGitOperations.ts` to bypass inaccessible files.
>     - Updates `CheckpointTracker.ts` to handle partial file additions without hanging.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=cline%2Fcline&utm_source=github&utm_medium=referral)<sup> for 2c1642105cad724599aa4004c8820e3a360c91a9. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: src/integrations/checkpoints/CheckpointTracker.ts [hunk 1]
```diff
@@ -157,7 +157,10 @@ class CheckpointTracker {
 
 			console.info(`Using shadow git at: ${gitPath}`)
 
-			await this.gitOperations.addCheckpointFiles(git)
+			const addFilesResult = await this.gitOperations.addCheckpointFiles(git)
+			if (!addFilesResult.success) {
+				console.error("Failed to add at least one file(s) to checkpoints shadow git")
```
Comment (saoudrizwan) [inline src/integrations/checkpoints/CheckpointTracker.ts:162]: should we not be breaking out of execution here by adding `return`? If the add files fails it proceeds as normal?

Comment (canvrno) [reply src/integrations/checkpoints/CheckpointTracker.ts:162]: By adding --ignore-errors to the git.add command in addCheckpointFiles(), Git will add all files except those that encounter a permissions error. If this happened In prior iterations of checkpoints, no files would be added, causing checkpoints to track nothing.

Currently, it does not output the specific files that were not added. To do that, we would either need to add files as an array (tried that before, it's to much in large repos) or enumerate untracked files afterward using 'git status'.

We could break out of execution here, or we could warn the user that "some" files were not included in the checkpoint and proceed. Given that a permissions issue is the likely failure scenario, it's unlikely these files are being modified by Cline.

**Review by dcbartlett — APPROVED** [review]

**Review by NightTrek — APPROVED** [review]
