### PR TITLE
Fix: Add role and aria-checked attributes to plan / act mode switch so that screen readers can tell its state ( Resolves #4244 )

### LINKED ISSUE #4244: [Accessibility Feature] current mode (plan / act) cannot be recognized by screen readers
### What happened?

When trying to change between plan and act, screen readers cannot tell which is currently active.

### Steps to reproduce

1. Try to focus on either of plan / act to see which is currently selected
2. Screen readers do not announce the active selection

### Relevant API REQUEST output

```shell

```

### Provider/Model

LiteLLM

### Operating System

Windows

### System Info

Screen readers: NVDA and Narrator tested

### Cline Version

v3.17.13

### Additional context

I'm almost sure that just adding aria-pressed and role="button" solves the issue. So I'm willing to submit a PR if accepted.

### PR DESCRIPTION
**Pull request by yncat**
### Related Issue

**Issue:** #4244 

### Description

When trying to change modes using a screen reader, it says "plan" or "act". However, it wasn't able to announce the  on / off state due to lack of aria attributes.
Also, there was a small problem that screen reader users couldn't notice that they were actually interactable, because the they were implemented with div elements without the correct role attribute.

Reference: the switch role https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/switch_role

### Test Procedure

- As I did in my previous pull request, it consists of aria / role attributes only. It won't affect the appearance of the controls.
- Tested using NVDA that the switch controls got announced "switch on plan" or "switch off plan" (same applies to act)

### Type of Change

-   [x] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [ ] ✨ New feature (non-breaking change which adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] ♻️ Refactor Changes
-   [ ] 💅 Cosmetic Changes
-   [ ] 📚 Documentation update
-   [ ] 🏃 Workflow Changes

### Pre-flight Checklist

-   [x] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [x] Tests are passing (`npm test`) and code is formatted and linted (`npm run format && npm run lint`)
-   [x] I have created a changeset using `npm run changeset` (required for user-facing changes)
-   [x] I have reviewed [contributor guidelines](https://github.com/cline/cline/blob/main/CONTRIBUTING.md)

### Additional Notes

----

> [!IMPORTANT]
> Add `role` and `aria-checked` attributes to plan/act mode switch in `ChatTextArea.tsx` for screen reader accessibility.
> 
>   - **Accessibility**:
>     - Add `role="switch"` and `aria-checked` attributes to `SwitchOption` in `ChatTextArea.tsx` for plan/act mode switch.
>     - Screen readers now announce "switch on plan" or "switch off plan" for the mode switch.
>   - **Testing**:
>     - Verified with NVDA screen reader that the switch state is announced correctly.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=cline%2Fcline&utm_source=github&utm_medium=referral)<sup> for f82a74e59fc5f06ced11b2417ba926d7bb05ba1c. You can [customize](https://app.ellipsis.dev/cline/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: webview-ui/src/components/chat/ChatTextArea.tsx [hunk 1]
```diff
@@ -1738,12 +1738,16 @@ const ChatTextArea = forwardRef<HTMLTextAreaElement, ChatTextAreaProps>(
 							<Slider isAct={chatSettings.mode === "act"} isPlan={chatSettings.mode === "plan"} />
 							<SwitchOption
 								isActive={chatSettings.mode === "plan"}
+								role="switch"
+								aria-checked={chatSettings.mode === "plan"}
```
Comment (yncat) [inline webview-ui/src/components/chat/ChatTextArea.tsx:1742]: [IMO]
Re-evaluating. This, and the one below could be refactored to be precalculated somewhere inside the functional component, but starting with the minimum changes. Please feel free to suggest refactoring.

**Comment by yncat** [comment]
Oh, might have missed something. Let me check

**Comment by yncat** [comment]
Guessing that just rerunning the job works, but looks like I don't have the privilege to do so.

**Review by 0xToshii — APPROVED** [review]
thanks for this!

File: webview-ui/src/components/chat/ChatTextArea.tsx (hunk 1 above)
Comment (0xToshii) [reply webview-ui/src/components/chat/ChatTextArea.tsx:1742]: good thought process, but i think it's okay as is
