### PR TITLE
Complete telemetry attribution for model/provider tracking

### LINKED ISSUE #1: README images
(ignore)

### LINKED ISSUE #2: Adding memory
First of all this is amazing! 

one thing that would be good though is if it had a chat history, i say this because i keep losing the task when im creating something. 

Similar to this, it would also be good for this to work on existing projects

### LINKED ISSUE #3: Rate Limit
I was working on the task and must have asked Claude to perform too many things in a short amount of time, or made a large request and hit a rate limit.

```
API request failed:
429 {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}
```

This stopped Claude Dev from working, and I could not stop the current action, or break out of the error message. In order to break out of this, I simply clicked the "+" button to start a new chat. Now there is no way to enter back into the previous chat thread, or pick up where I left off.

Thoughts on this? Am I doing anything wrong, or missing something obvious (for resuming a chat thread)? (I have now read the docs discussing rate limits, so I understand that part now).

Any help is much appreciated! Very slick tool so far!! 😎

### LINKED ISSUE #5: Issue while building a simple flask user login application
App is Good. But the majority of the time getting this error
for building a simple flask user login app.

API request failed: 400 {"type":"error","error":{"type":"invalid_request_error","message":"Output blocked by content filtering policy"}}

### LINKED ISSUE #6: Can you add OpenRouter Support?

### PR DESCRIPTION
**Pull request by nickbaumann98**
### Related Issue

**Issue:** Completes telemetry attribution work from PR #7214

### Description

This PR completes the model and provider attribution work started in PR #7214 by adding tracking fields to the remaining telemetry events. These changes enable more granular analytics by ensuring all telemetry events consistently capture which model and provider were used.

**Changes:**
- Add provider parameter to diff edit failure events
- Add provider parameter to context summarization events  
- Add mode parameter to conversation turn events
- Add model/provider parameters to checkpoint events
- Add model/provider parameters to focus chain completion events

**Implementation approach:**
- Follows the exact pattern established in PR #7214
- Extracts provider information using the plan/act mode configuration
- Uses "unknown" placeholders for checkpoint events that occur outside API call context (e.g., initialization, user-triggered restores)
- All changes are backward compatible with no breaking changes

### Test Procedure

**Static Analysis:**
- ✅ TypeScript compilation passes with no errors
- ✅ All method signatures are consistent
- ✅ No linter warnings

**Code Review:**
- Manually verified all 9 modified files follow established patterns
- Confirmed parameter extraction logic matches PR #7214
- Validated all call sites are updated correctly

**Live Testing:**
Requires production PostHog credentials for full validation. Recommended team testing:
1. Verify new event properties appear in PostHog
2. Confirm no telemetry regressions
3. Test analytics queries work with new fields

### Type of Change

- [x] ♻️ Refactor Changes
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 💅 Cosmetic Changes
- [ ] 📚 Documentation update
- [ ] 🏃 Workflow Changes

### Pre-flight Checklist

- [x] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
- [x] Tests are passing (`npm test`) and code is formatted and linted (`npm run format && npm run lint`)
- [ ] I have created a changeset using `npm run changeset` (required for user-facing changes)
- [x] I have reviewed [contributor guidelines](https://github.com/cline/cline/blob/main/CONTRIBUTING.md)

### Screenshots

Not applicable - backend telemetry changes with no UI impact.

### Additional Notes

**Files Modified:**
- `src/services/telemetry/TelemetryService.ts` - Updated 5 method signatures
- `src/core/task/tools/handlers/WriteToFileToolHandler.ts` - Fix #1
- `src/core/task/tools/handlers/SummarizeTaskHandler.ts` - Fix #2
- `src/core/task/index.ts` - Fix #3 and #6
- `src/integrations/checkpoints/CheckpointTracker.ts` - Fix #5
- `src/integrations/checkpoints/CheckpointGitOperations.ts` - Fix #5
- `src/integrations/checkpoints/index.ts` - Fix #5
- `src/integrations/checkpoints/MultiRootCheckpointManager.ts` - Fix #5
- `src/core/task/focus-chain/index.ts` - Fix #6

This completes the telemetry attribution initiative, ensuring consistent model/provider tracking across all event types for improved analytics capabilities.

----

> [!IMPORTANT]
> Add model and provider tracking to various telemetry events for consistent data capture across event types.
> 
>   - **Behavior**:
>     - Add `provider` parameter to diff edit failure events in `WriteToFileToolHandler`.
>     - Add `provider` parameter to context summarization events in `SummarizeTaskHandler`.
>     - Add `mode` parameter to conversation turn events in `Task`.
>     - Add `model/provider` parameters to checkpoint events in `CheckpointTracker` and `CheckpointGitOperations`.
>     - Add `model/provider` parameters to focus chain completion events in `FocusChainManager`.
>   - **Telemetry**:
>     - Update `captureConversationTurnEvent()` in `TelemetryService` to include `mode`.
>     - Update `captureSummarizeTask()` in `TelemetryService` to include `provider`.
>     - Update `captureCheckpointUsage()` in `TelemetryService` to include `modelId` and `provider`.
>     - Update `captureDiffEditFailure()` in `TelemetryService` to include `provider`.
>     - Update `captureFocusChainIncompleteOnCompletion()` in `TelemetryService` to include `modelId` and `provider`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=cline%2Fcline&utm_source=github&utm_medium=referral)<sup> for 7a772a50421b2b8ba222f2d643f4d60427be2ee9. You can [customize](https://app.ellipsis.dev/cline/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by canvrno** [comment]
With these changes, the checkpoints telemetry is always going to collect events with "unknown" as the provider ID. We should remove this, as checkpoints are part of the Cline core task loop, and their behavior is not model/provider dependent.

File: src/services/telemetry/TelemetryService.ts [hunk 1]
```diff
@@ -761,11 +772,15 @@ export class TelemetryService {
...
 	 * @param action The type of checkpoint action
+	 * @param modelId The model ID being used
+	 * @param provider The API provider being used
 	 * @param durationMs Optional duration of the operation in milliseconds
 	 */
 	public captureCheckpointUsage(
 		ulid: string,
 		action: "shadow_git_initialized" | "commit_created" | "restored" | "diff_generated",
+		modelId: string,
+		provider: string,
```
Comment (canvrno) [inline src/services/telemetry/TelemetryService.ts]: This should be removed, and all `captureCheckpointUsage() `calls updated accordingly

Comment (nickbaumann98) [reply src/services/telemetry/TelemetryService.ts]: Just pushed an update to the PR removing all provider & model telemetry tracking from checkpoints

File: src/core/task/tools/handlers/WriteToFileToolHandler.ts [hunk 2]
```diff
@@ -43,7 +43,7 @@ export class WriteToFileToolHandler implements IFullyManagedTool {
 		const config = uiHelpers.getConfig()
 
 		// Creates file if it doesn't exist, and opens editor to stream content in. We don't want to handle this in the try/catch below since the error handler for it resets the diff view, which wouldn't be open if this failed.
-		const result = await this.validateAndPrepareFileOperation(config, block, rawRelPath, rawDiff, rawContent)
+		const result = await this.validateAndPrepareFileOperation(config, block, rawRelPath, rawDiff, rawContent, undefined)
```
Comment (canvrno) [inline src/core/task/tools/handlers/WriteToFileToolHandler.ts]: We could extract the provider here and provide it as is being done elsewhere, or do it in validateAndPrepareFileOperation()

**Review by canvrno — APPROVED** [review]

**Review by canvrno — APPROVED** [review]
